version: '3.8'
services:
  db:
    image: postgres:latest  # Use the latest version of PostgreSQL
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres           # Replace with your desired username
      POSTGRES_PASSWORD: postgres   # Replace with your desired password
      POSTGRES_DB: postgres         # Replace with your desired database name
    ports:
      - "5432:5432"                   # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - my_network
volumes:
  postgres_data:
networks:
  my_network:
    driver: bridge
